version: '3.8'

services:
  db:
    container_name: postgresql_db
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  web:
    container_name: web
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload"
    ports:
      - "8003:8003"
    volumes:
      - ./:/app
    depends_on:
      - db
      - pgadmin
    restart: always

volumes:
  postgres_data:
    driver: local
